module Seedy
  module Generators
    DEPARTMENTS = [
     "Landscape Grounds Shop",
     "Cap and Gown Club",
     "Other Affiliates",
     "Chemical Engineering",
     "Board of Trustees",
     "Forbes College",
     "Undergraduate Class of 2007",
     "Investment Income",
     "Systems and Technical Support",
     "Special Facilities  EQuad",
     "Accelerator",
     "Princeton Materials Institute",
     "Agency Accounts",
     "Undergraduate Class of 2008",
     "McCarter Theatre",
     "Undergraduate Class of 2009",
     "FY 2007 Operating Major Maintenance",
     "Center for Teaching and Learning",
     "Cloister Inn",
     "Wesley Foundation",
     "Princeton Neuroscience Institute",
     "Biochemical Sciences",
     "Building Services  Forrestal Campus",
     "BricaBrac Yearbook and Nassau Herald",
     "B'Nai B'Rith Hillel Foundation",
     "Alumni Colleges",
     "Cell and Developmental Biology",
     "Master's Leave Program",
     "Human Resources",
     "Tiger Net",
     "Lutheran Chaplaincy",
     "Center for Jewish Life",
     "Graduate Student Loans Committed",
     "Sustainability",
     "History",
     "Gifts and Grants",
     "Gift Planning",
     "Elm Club",
     "University League Nursery School",
     "Center for the Study of Religion",
     "Office of the Dean of the Graduate School",
     "Nassau East",
     "Mechanical and Aerospace Engineering MAE",
     "Transportation and Parking Services",
     "Council on Regional Studies",
     "Office of Public Affairs",
     "Career Services",
     "Army Officer Education Program",
     "Other",
     "Office of the Vice President and Secretary",
     "Pace Center",
     "Library",
     "Development Project Services",
     "Princeton Forrestal Center Funds Advanced",
     "Peter B Lewis Center for the Arts",
     "Princeton University Federal Credit Union",
     "Development Events",
     "Alumni Records",
     "Development Administration",
     "Facilities  NonShop Expenses",
     "Princeton Broadcasting Service",
     "Invested Collateral Funds",
     "Mechanical and Aerospace Engineering",
     "History of Science",
     "Aquinas Institute",
     "Plumbing Shop",
     "Undergraduate Student Government",
     "1998 Major Maintenance",
     "Sponsored Research Accounting",
     "Outside computer user",
     "Daily Princetonian",
     "Princeton University Investment Company",
     "Richardson Auditorium",
     "Vice President and Senior Adviser",
     "OIT Information Systems",
     "University Press Club",
     "Frist Campus Center Shadow",
     "Princeton in Beijing",
     "Freshman Seminar Program",
     "Deferred Charges and Revolving Funds",
     "Princeton University Press",
     "Religious Life",
     "International Economics",
     "Miscellaneous Accounts Receivable",
     "Unappropriated  Estimated Income",
     "Program in Law and Public Affairs",
     "English",
     "Civil and Environmental Engineering CEE",
     "General Reserve",
     "2003 Major Maintenance",
     "Office of Design and Construction",
     "Papers of Thomas Jefferson",
     "Tigertones",
     "University NOW Day Nursery",
     "1999 Major Maintenance",
     "Wilson College",
     "The Office of Information Technology \n",
     "Dining Services Income",
     "East Asian Studies",
     "Princeton Environmental Institute",
     "Undergraduate Class withheld",
     "Conference and Event Services",
     "Federal Parent Loan",
     "Accounts Receivable  Undergraduate Students",
     "Princeton Prospect Foundation",
     "Colonial Club",
     "Petty Cash Fund",
     "Distributed Management Systems",
     "1997 Major Maintenance",
     "Psychology",
     "Laboratory Animal Resources",
     "FY 2005 Operating Major Maintenance",
     "Nassau Weekly",
     "Graduate Student Loans In Process",
     "US Geological Survey",
     "Tiger Inn",
     "Development Communications",
     "Stevenson Hall",
     "Lock Shop",
     "PrincetoninAsia Program",
     "Program in Judaic Studies",
     "Unallocated Academic Departments",
     "Office of the Dean of Undergraduate Students",
     "Rockefeller Public Service Awards",
     "Credit Union",
     "WalkerGordon South",
     "Office of the Registrar",
     "Applied and Computational Mathematics",
     "Retirees",
     "Student Volunteers Council",
     "Associate Treasurer for Operations",
     "Office of the Provost",
     "Astrophysical Sciences",
     "American WhigCliosophic Society",
     "Special Facilities  Frick/Hoyt",
     "FY 1999 Operating Major Maintenance",
     "Campaign Expense",
     "Information Services",
     "Alumni and Donor Records",
     "Forrestal Campus  100 Acres",
     "Gift Receivables",
     "Tower Club",
     "Bank Transfers",
     "Electrical Engineering",
     "Princeton Footnotes",
     "Post Doctoral Fellowships",
     "Disability Services",
     "Special Facilities  Jadwin/Fine",
     "Due From US Government",
     "Phipps",
     "Faculty Allowances",
     "Special Facilities  Firestone Library",
     "Life Income Funds",
     "Baptist Chaplaincy",
     "University Machine Shops",
     "Capital Income",
     "Unallocated Office of Information Technology",
     "Computer Science",
     "Office of Safety and Administration",
     "Rockefeller College",
     "Quadrangle Club",
     "Campaign Relations",
     "University Reserve",
     "Invested Operating Funds",
     "Roofing and Tin Shop",
     "Investments  Life Income",
     "Student Agencies",
     "Graduate Student Apartments Income",
     "Program in Theater",
     "Continuing EducationSpecial Programs",
     "Public Lectures",
     "Real Estate Development",
     "Industrial Relations",
     "Development Relations",
     "Tigerlilies",
     "Graduate School Fellowships",
     "Center for African American Studies",
     "Unallocated Plant",
     "Romance Languages and Literatures",
     "Athletics Income",
     "Music",
     "Triangle Club",
     "Maintenance  Faculty and Staff Housing",
     "FY 2006 Operating Major Maintenance",
     "Paint Shop",
     "Information Strategy",
     "Life Safety and Security Systems",
     "Undergraduate Class of 2010",
     "Office of the Vice President for Development",
     "Greenhouse Grounds Shop",
     "Chapel  Director of Music",
     "Office of the Dean of the College",
     "French and Italian",
     "Writing Program",
     "Undergraduate Class of 2011",
     "Council on Environmental Studies",
     "Gifts In Kind",
     "TigerCard Office",
     "Loan Control",
     "Center of International Studies",
     "Molecular Biology",
     "OffSite Research Plasma Physics Laboratory",
     "Central Campus Grounds Shop",
     "Undergraduate Class of 2013",
     "Office of Research and Project Administration",
     "Project Managers",
     "Office of Development Priorities",
     "Tigernet Office of Information Technology",
     "Undergraduate Class of 2014",
     "Office of the President",
     "Carpenter Shop",
     "Statistics",
     "Leadership Gifts",
     "Counseling Center",
     "Building Services",
     "Politics",
     "Investments  Secondary Pool",
     "Accounts Payable",
     "Partnership 2000",
     "Renewal and Replacement Reserve",
     "Westminster Foundation",
     "Special Facilities  Forrestal Maintenance",
     "Not Applicable",
     "Religion",
     "Development Information Systems",
     "NonAffiliates",
     "Unallocated University Services",
     "Prize Fellowship",
     "Real Estate",
     "Pew Science Program",
     "Business Operations Plasma Physics Laboratory",
     "Continuing Education",
     "Printing University Services",
     "Simulated Games",
     "Due From Brokers",
     "Office of the Executive Vice President",
     "Dial Elm and Cannon Clubs",
     "Office of Technology Licensing",
     "Davis International Center",
     "Community House",
     "Creative Writing",
     "Salary Pool  General Funds",
     "Mail Services",
     "Office of the Dean of the Faculty",
     "Unallocated General Administration",
     "Garage  Main Campus",
     "Geosciences",
     "Center for Study of Human Values",
     "2005 Major Maintenance",
     "Parent Authorization",
     "Anthropology",
     "Office of Audit and Compliance",
     "Restricted Funds",
     "Due To Brokers",
     "Fire Protection Shop",
     "Environmental Health and Safety",
     "Alumni Council",
     "Philosophy",
     "Mellon Education Grant",
     "Investments  Funds Separately Invested FSI",
     "Foundation for Student Communication",
     "Unapplied Loan Payments",
     "Security Deposits and Deferred Revenue",
     "Program in Linguistics",
     "Women's Studies",
     "Principal  Primary Pool",
     "Science in Human Affairs",
     "Long Term Debt Payable",
     "University Archives",
     "Public Safety",
     "Undergraduate Financial Aid",
     "Short Term Strategy",
     "International Center",
     "A service of OIT Network Systems \n",
     "Admission",
     "PPL Employee Benefits",
     "Office of the Controller",
     "Survey Research Center",
     "Visual Arts",
     "Classics",
     "Theater Program",
     "Restaurant Associates",
     "FY 2002 Operating Major Maintenance",
     "Educational Programs",
     "Outside Matching Fellowships",
     "FY 2004 Operating Major Maintenance",
     "Bendheim Center for Finance",
     "Alumni Records and Mailing",
     "Business Today Magazine",
     "Purchasing",
     "Federal Work Study",
     "Student Health Plan",
     "Special Student",
     "Printing Services",
     "Nassoons",
     "Slavic Languages and Literatures",
     "Outside department",
     "Maintenance  Forrestal Campus",
     "Collateral and Loaned Stocks",
     "OIT Partnership 2000",
     "Planning and Operations",
     "Graduate Student Union",
     "Student Notes In Process",
     "Pride Alliance",
     "Utility Plant",
     "Educational Technologies Center",
     "CIT Budget and Finance",
     "Dept Transfer",
     "Summer Fellowships",
     "FY 1998 Operating Major Maintenance",
     "University General Expenses",
     "Whitman College",
     "Principal  Student Loan Funds",
     "Departmental Savings",
     "Research Department Plasma Physics Laboratory",
     "Princeton Center for Theoretical Science",
     "Residential Colleges",
     "Stewardship",
     "Allowance For Contingency",
     "Undergraduate Class of 2006"]

    def department
      DEPARTMENTS[rand(DEPARTMENTS.length - 1)]
    end
  end
end
